steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile
      - --build-arg
      - NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}
      - --build-arg
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - --build-arg
      - NEXT_PUBLIC_POSTHOG_KEY=${_NEXT_PUBLIC_POSTHOG_KEY}
      - --build-arg
      - NEXT_PUBLIC_POSTHOG_HOST=${_NEXT_PUBLIC_POSTHOG_HOST}
      - --build-arg
      - NEXT_PUBLIC_DATAFAST_WEBSITE_ID=${_NEXT_PUBLIC_DATAFAST_WEBSITE_ID}
      - --build-arg
      - NEXT_PUBLIC_DATAFAST_DOMAIN=${_NEXT_PUBLIC_DATAFAST_DOMAIN}
      - -t
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA
      - --region
      - ${_DEPLOY_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --port
      - "8080"
      - --cpu
      - "2"
      - --memory
      - "2Gi"
      - --cpu-boost
      - --quiet
      - --update-labels
      - managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID
      - --update-env-vars
      - NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL},NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY},NEXT_PUBLIC_POSTHOG_KEY=${_NEXT_PUBLIC_POSTHOG_KEY},NEXT_PUBLIC_POSTHOG_HOST=${_NEXT_PUBLIC_POSTHOG_HOST},NEXT_PUBLIC_DATAFAST_WEBSITE_ID=${_NEXT_PUBLIC_DATAFAST_WEBSITE_ID},NEXT_PUBLIC_DATAFAST_DOMAIN=${_NEXT_PUBLIC_DATAFAST_DOMAIN},CHART_RENDER_SERVICE_URL=${_CHART_RENDER_SERVICE_URL},CHART_RENDER_API_KEY=${_CHART_RENDER_API_KEY},WEALTH_MONITOR_ENABLED=false

images:
  - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA

substitutions:
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _AR_PROJECT_ID: project-bf065c0a-e475-47c4-b25
  _AR_REPOSITORY: cloud-run-source-deploy
  _REPO_NAME: terabitsai
  _SERVICE_NAME: ai-agent-platform-web
  _DEPLOY_REGION: us-central1
  _NEXT_PUBLIC_SUPABASE_URL: https://wsxzbqfeafzccprlllpu.supabase.co
  _NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzeHpicWZlYWZ6Y2NwcmxsbHB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE2NTEzNjksImV4cCI6MjA5NzIyNzM2OX0.Z38OBV7d1ki6SD298NzRcQMsEHuit7WGhf4yA3-XqPM
  _CHART_RENDER_SERVICE_URL: https://ai-agent-platform-chart-renderer-73vs3tcpga-uc.a.run.app
  _CHART_RENDER_API_KEY: 9a231d279b468c6d25c438a0e19ce73d20c3d977ebd36ce6
  _NEXT_PUBLIC_POSTHOG_KEY: phc_LS2kQaXRp32gNXmNbFHjjrNDTOkLxtpURqjH0nTzyRu
  _NEXT_PUBLIC_POSTHOG_HOST: https://us.i.posthog.com
  _NEXT_PUBLIC_DATAFAST_WEBSITE_ID: dfid_Gm4iXErEaymGfrlQMMHEh
  _NEXT_PUBLIC_DATAFAST_DOMAIN: terabitsai.com

options:
  logging: CLOUD_LOGGING_ONLY
