import { stableStaticAssetId } from "./stable-asset-id";
import type { AssetRow } from "./types";

const CRYPTO_RAW = [
  { symbol: "BTCUSD", name: "Bitcoin / USD CFD" },
  { symbol: "ETHUSD", name: "Ethereum / USD CFD" },
  { symbol: "SOLUSD", name: "Solana / USD CFD" },
  { symbol: "XRPUSD", name: "Ripple / USD CFD" },
  { symbol: "ADAUSD", name: "Cardano / USD CFD" },
  { symbol: "DOGEUSD", name: "Dogecoin / USD CFD" },
  { symbol: "DOTUSD", name: "Polkadot / USD CFD" },
  { symbol: "AVAXUSD", name: "Avalanche / USD CFD" },
  { symbol: "LTCUSD", name: "Litecoin / USD CFD" },
  { symbol: "LINKUSD", name: "Chainlink / USD CFD" },
  { symbol: "UNIUSD", name: "Uniswap / USD CFD" },
  { symbol: "NEARUSD", name: "Near Protocol / USD CFD" },
  { symbol: "PEPEUSD", name: "Pepe / USD CFD" },
  { symbol: "FILUSD", name: "Filecoin / USD CFD" },
  { symbol: "LDOUSD", name: "Lido DAO / USD CFD" },
  { symbol: "OPUSD", name: "Optimism / USD CFD" },
  { symbol: "ARBUSD", name: "Arbitrum / USD CFD" },
  { symbol: "GRTUSD", name: "The Graph / USD CFD" },
  { symbol: "APTUSD", name: "Aptos / USD CFD" },
  { symbol: "ICPUSD", name: "Internet Computer / USD CFD" },
  { symbol: "ETCUSD", name: "Ethereum Classic / USD CFD" },
  { symbol: "XLMUSD", name: "Stellar Lumens / USD CFD" },
  { symbol: "CROUSD", name: "Cronos / USD CFD" },
  { symbol: "HBARUSD", name: "Hedera Hashgraph / USD CFD" },
  { symbol: "ATOMUSD", name: "Cosmos / USD CFD" },
  { symbol: "FTMUSD", name: "Fantom / USD CFD" },
  { symbol: "IMXUSD", name: "Immutable X / USD CFD" },
  { symbol: "ALGOUSD", name: "Algorand / USD CFD" },
  { symbol: "VETUSD", name: "VeChain / USD CFD" },
  { symbol: "RNDRUSD", name: "Render Token / USD CFD" },
  { symbol: "STXUSD", name: "Stacks / USD CFD" },
  { symbol: "MKRUSD", name: "Maker / USD CFD" },
  { symbol: "AAVEUSD", name: "Aave / USD CFD" },
  { symbol: "SUIUSD", name: "Sui / USD CFD" },
  { symbol: "TIAUSD", name: "Celestia / USD CFD" },
  { symbol: "INJUSD", name: "Injective / USD CFD" },
  { symbol: "SEIUSD", name: "Sei / USD CFD" },
  { symbol: "JUPUSD", name: "Jupiter / USD CFD" },
  { symbol: "WIFUSD", name: "dogwifhat / USD CFD" },
  { symbol: "FLOKIUSD", name: "Floki / USD CFD" },
  { symbol: "BONKUSD", name: "Bonk / USD CFD" },
  { symbol: "PYTHUSD", name: "Pyth Network / USD CFD" },
  { symbol: "MINAUSD", name: "Mina / USD CFD" },
  { symbol: "EOSUSD", name: "EOS / USD CFD" },
  { symbol: "THETAUSD", name: "Theta Network / USD CFD" },
  { symbol: "SANDUSD", name: "The Sandbox / USD CFD" },
  { symbol: "MANAUSD", name: "Decentraland / USD CFD" },
  { symbol: "AXSUSD", name: "Axie Infinity / USD CFD" },
  { symbol: "GALAUSD", name: "Gala / USD CFD" },
  { symbol: "FETUSD", name: "Fetch.ai / USD CFD" }
];

const STOCKS_RAW = [
  { symbol: "AAPL", name: "Apple Inc. CFD" },
  { symbol: "MSFT", name: "Microsoft Corp. CFD" },
  { symbol: "TSLA", name: "Tesla Inc. CFD" },
  { symbol: "NVDA", name: "NVIDIA Corp. CFD" },
  { symbol: "AMZN", name: "Amazon.com Inc. CFD" },
  { symbol: "GOOGL", name: "Alphabet Inc. Class A CFD" },
  { symbol: "GOOG", name: "Alphabet Inc. Class C CFD" },
  { symbol: "META", name: "Meta Platforms Inc. CFD" },
  { symbol: "NFLX", name: "Netflix Inc. CFD" },
  { symbol: "AMD", name: "Advanced Micro Devices CFD" },
  { symbol: "INTC", name: "Intel Corp. CFD" },
  { symbol: "PYPL", name: "PayPal Holdings CFD" },
  { symbol: "DIS", name: "Walt Disney Co. CFD" },
  { symbol: "SBUX", name: "Starbucks Corp. CFD" },
  { symbol: "NKE", name: "Nike Inc. CFD" },
  { symbol: "KO", name: "Coca-Cola Co. CFD" },
  { symbol: "PEP", name: "PepsiCo Inc. CFD" },
  { symbol: "WMT", name: "Walmart Inc. CFD" },
  { symbol: "TSM", name: "Taiwan Semiconductor CFD" },
  { symbol: "BABA", name: "Alibaba Group CFD" },
  { symbol: "ASML", name: "ASML Holding CFD" },
  { symbol: "JPM", name: "JPMorgan Chase & Co. CFD" },
  { symbol: "BAC", name: "Bank of America CFD" },
  { symbol: "V", name: "Visa Inc. CFD" },
  { symbol: "MA", name: "Mastercard Inc. CFD" },
  { symbol: "LLY", name: "Eli Lilly & Co. CFD" },
  { symbol: "UNH", name: "UnitedHealth Group CFD" },
  { symbol: "HD", name: "Home Depot Inc. CFD" },
  { symbol: "COST", name: "Costco Wholesale CFD" },
  { symbol: "CVX", name: "Chevron Corp. CFD" },
  { symbol: "XOM", name: "Exxon Mobil Corp. CFD" },
  { symbol: "JNJ", name: "Johnson & Johnson CFD" },
  { symbol: "PG", name: "Procter & Gamble CFD" },
  { symbol: "MRK", name: "Merck & Co. CFD" },
  { symbol: "PFE", name: "Pfizer Inc. CFD" },
  { symbol: "ABBV", name: "AbbVie Inc. CFD" },
  { symbol: "AVGO", name: "Broadcom Inc. CFD" },
  { symbol: "ADBE", name: "Adobe Inc. CFD" },
  { symbol: "CRM", name: "Salesforce Inc. CFD" },
  { symbol: "ORCL", name: "Oracle Corp. CFD" },
  { symbol: "CSCO", name: "Cisco Systems CFD" },
  { symbol: "QCOM", name: "Qualcomm Inc. CFD" },
  { symbol: "TXN", name: "Texas Instruments CFD" },
  { symbol: "AMAT", name: "Applied Materials CFD" },
  { symbol: "MU", name: "Micron Technology CFD" },
  { symbol: "LRCX", name: "Lam Research CFD" },
  { symbol: "NOW", name: "ServiceNow Inc. CFD" },
  { symbol: "PANW", name: "Palo Alto Networks CFD" },
  { symbol: "FTNT", name: "Fortinet Inc. CFD" },
  { symbol: "CRWD", name: "CrowdStrike Holdings CFD" },
  { symbol: "DDOG", name: "Datadog Inc. CFD" },
  { symbol: "NET", name: "Cloudflare Inc. CFD" },
  { symbol: "OKTA", name: "Okta Inc. CFD" },
  { symbol: "SNOW", name: "Snowflake Inc. CFD" },
  { symbol: "ABNB", name: "Airbnb Inc. CFD" },
  { symbol: "UBER", name: "Uber Technologies CFD" },
  { symbol: "LYFT", name: "Lyft Inc. CFD" },
  { symbol: "DASH", name: "DoorDash Inc. CFD" },
  { symbol: "CART", name: "Instacart CFD" },
  { symbol: "COIN", name: "Coinbase Global CFD" },
  { symbol: "HOOD", name: "Robinhood Markets CFD" },
  { symbol: "SQ", name: "Block Inc. (Square) CFD" },
  { symbol: "SOFI", name: "SoFi Technologies CFD" },
  { symbol: "PLTR", name: "Palantir Technologies CFD" },
  { symbol: "RIVN", name: "Rivian Automotive CFD" },
  { symbol: "LCID", name: "Lucid Group CFD" },
  { symbol: "NIO", name: "Nio Inc. CFD" },
  { symbol: "XPEV", name: "Xpeng Inc. CFD" },
  { symbol: "LI", name: "Li Auto Inc. CFD" },
  { symbol: "JD", name: "JD.com Inc. CFD" },
  { symbol: "PDD", name: "PDD Holdings CFD" },
  { symbol: "BIDU", name: "Baidu Inc. CFD" },
  { symbol: "SE", name: "Sea Ltd CFD" },
  { symbol: "MELI", name: "MercadoLibre CFD" },
  { symbol: "SHOP", name: "Shopify Inc. CFD" },
  { symbol: "SPOT", name: "Spotify Technology CFD" },
  { symbol: "ROKU", name: "Roku Inc. CFD" },
  { symbol: "ZM", name: "Zoom Video CFD" },
  { symbol: "DOCU", name: "DocuSign Inc. CFD" },
  { symbol: "DKNG", name: "DraftKings Inc. CFD" },
  { symbol: "GME", name: "GameStop Corp. CFD" },
  { symbol: "AMC", name: "AMC Entertainment CFD" },
  { symbol: "MARA", name: "MARA Holdings CFD" },
  { symbol: "RIOT", name: "Riot Platforms CFD" },
  { symbol: "MSTR", name: "MicroStrategy Inc. CFD" },
  { symbol: "NVIDIA", name: "NVIDIA (Double) CFD" },
  { symbol: "GE", name: "General Electric CFD" },
  { symbol: "F", name: "Ford Motor Co. CFD" },
  { symbol: "GM", name: "General Motors CFD" },
  { symbol: "CAT", name: "Caterpillar Inc. CFD" },
  { symbol: "DE", name: "Deere & Co. CFD" },
  { symbol: "MMM", name: "3M Company CFD" },
  { symbol: "HON", name: "Honeywell CFD" },
  { symbol: "BA", name: "Boeing Co. CFD" },
  { symbol: "LMT", name: "Lockheed Martin CFD" },
  { symbol: "RTX", name: "RTX Corp. CFD" },
  { symbol: "NOC", name: "Northrop Grumman CFD" },
  { symbol: "GD", name: "General Dynamics CFD" },
  { symbol: "BP", name: "BP PLC CFD" },
  { symbol: "SHEL", name: "Shell PLC CFD" },
  { symbol: "COP", name: "ConocoPhillips CFD" },
  { symbol: "SLB", name: "Schlumberger CFD" },
  { symbol: "HAL", name: "Halliburton CFD" },
  { symbol: "UNP", name: "Union Pacific CFD" },
  { symbol: "UPS", name: "United Parcel Service CFD" },
  { symbol: "FDX", name: "FedEx Corp. CFD" },
  { symbol: "T", name: "AT&T Inc. CFD" },
  { symbol: "VZ", name: "Verizon CFD" },
  { symbol: "TMUS", name: "T-Mobile US CFD" },
  { symbol: "CMG", name: "Chipotle Mexican Grill CFD" },
  { symbol: "MCD", name: "McDonald's Corp. CFD" },
  { symbol: "NPSNY", name: "Naspers Ltd CFD" },
  { symbol: "TENCENT", name: "Tencent Holdings CFD" },
  { symbol: "SONY", name: "Sony Group CFD" },
  { symbol: "HMC", name: "Honda Motor CFD" },
  { symbol: "TOYOF", name: "Toyota Motor CFD" },
  { symbol: "AIRFP", name: "Airbus SE CFD" },
  { symbol: "BMW", name: "Bayerische Motoren Werke CFD" },
  { symbol: "DAI", name: "Mercedes-Benz Group CFD" },
  { symbol: "VOW", name: "Volkswagen AG CFD" }
];

const INDICES_COMM_FOREX_RAW = [
  // Indices
  { symbol: "US500", name: "US 500 CFD", class: "etf", sector: "Indices" },
  { symbol: "US100", name: "US Tech 100 CFD", class: "etf", sector: "Indices" },
  { symbol: "US30", name: "US Wall Street 30 CFD", class: "etf", sector: "Indices" },
  { symbol: "UK100", name: "UK 100 CFD", class: "etf", sector: "Indices" },
  { symbol: "DE40", name: "Germany 40 CFD", class: "etf", sector: "Indices" },
  { symbol: "FR40", name: "France 40 CFD", class: "etf", sector: "Indices" },
  { symbol: "JP225", name: "Japan 225 CFD", class: "etf", sector: "Indices" },
  { symbol: "HK50", name: "Hong Kong 50 CFD", class: "etf", sector: "Indices" },
  { symbol: "ES35", name: "Spain 35 CFD", class: "etf", sector: "Indices" },
  { symbol: "IT40", name: "Italy 40 CFD", class: "etf", sector: "Indices" },
  { symbol: "EU50", name: "EU Stocks 50 CFD", class: "etf", sector: "Indices" },
  { symbol: "AU200", name: "Australia 200 CFD", class: "etf", sector: "Indices" },
  { symbol: "US2000", name: "US Russel 2000 CFD", class: "etf", sector: "Indices" },
  { symbol: "CN50", name: "China A50 CFD", class: "etf", sector: "Indices" },
  { symbol: "HKGTECH", name: "Hong Kong Tech Index CFD", class: "etf", sector: "Indices" },
  { symbol: "HSCEI", name: "China H-Shares CFD", class: "etf", sector: "Indices" },
  { symbol: "SG25", name: "Singapore 25 CFD", class: "etf", sector: "Indices" },
  { symbol: "DXY", name: "US Dollar Index CFD", class: "etf", sector: "Indices" },
  { symbol: "VIX", name: "Volatility Index CFD", class: "etf", sector: "Indices" },
  { symbol: "CH20", name: "Switzerland 20 CFD", class: "etf", sector: "Indices" },
  { symbol: "NL25", name: "Netherlands 25 CFD", class: "etf", sector: "Indices" },
  { symbol: "FANG", name: "US Fang CFD", class: "etf", sector: "Indices" },
  
  // Commodities
  { symbol: "GOLD", name: "Gold Spot CFD", class: "etf", sector: "Commodities" },
  { symbol: "SILVER", name: "Silver Spot CFD", class: "etf", sector: "Commodities" },
  { symbol: "OIL_CRUDE", name: "WTI Crude Oil CFD", class: "etf", sector: "Commodities" },
  { symbol: "OIL_BRENT", name: "Brent Crude Oil CFD", class: "etf", sector: "Commodities" },
  { symbol: "NATURAL_GAS", name: "Natural Gas CFD", class: "etf", sector: "Commodities" },
  { symbol: "COPPER", name: "Copper CFD", class: "etf", sector: "Commodities" },
  { symbol: "PLATINUM", name: "Platinum CFD", class: "etf", sector: "Commodities" },
  { symbol: "PALLADIUM", name: "Palladium CFD", class: "etf", sector: "Commodities" },
  { symbol: "CORN", name: "Corn CFD", class: "etf", sector: "Commodities" },
  { symbol: "WHEAT", name: "Wheat CFD", class: "etf", sector: "Commodities" },
  { symbol: "SOYBEANS", name: "Soybeans CFD", class: "etf", sector: "Commodities" },
  { symbol: "SUGAR", name: "Sugar CFD", class: "etf", sector: "Commodities" },
  { symbol: "COFFEE", name: "Coffee CFD", class: "etf", sector: "Commodities" },
  { symbol: "COCOA", name: "Cocoa CFD", class: "etf", sector: "Commodities" },
  { symbol: "COTTON", name: "Cotton CFD", class: "etf", sector: "Commodities" },

  // Forex
  { symbol: "EURUSD", name: "EUR/USD CFD", class: "etf", sector: "Forex" },
  { symbol: "GBPUSD", name: "GBP/USD CFD", class: "etf", sector: "Forex" },
  { symbol: "USDJPY", name: "USD/JPY CFD", class: "etf", sector: "Forex" },
  { symbol: "AUDUSD", name: "AUD/USD CFD", class: "etf", sector: "Forex" },
  { symbol: "USDCAD", name: "USD/CAD CFD", class: "etf", sector: "Forex" },
  { symbol: "USDCHF", name: "USD/CHF CFD", class: "etf", sector: "Forex" },
  { symbol: "NZDUSD", name: "NZD/USD CFD", class: "etf", sector: "Forex" },
  { symbol: "EURGBP", name: "EUR/GBP CFD", class: "etf", sector: "Forex" },
  { symbol: "EURJPY", name: "EUR/JPY CFD", class: "etf", sector: "Forex" },
  { symbol: "GBPJPY", name: "GBP/JPY CFD", class: "etf", sector: "Forex" },
  { symbol: "AUDJPY", name: "AUD/JPY CFD", class: "etf", sector: "Forex" },
  { symbol: "CADJPY", name: "CAD/JPY CFD", class: "etf", sector: "Forex" },
  { symbol: "CHFJPY", name: "CHF/JPY CFD", class: "etf", sector: "Forex" },
  { symbol: "EURCHF", name: "EUR/CHF CFD", class: "etf", sector: "Forex" },
  { symbol: "EURAUD", name: "EUR/AUD CFD", class: "etf", sector: "Forex" },
  { symbol: "GBPAUD", name: "GBP/AUD CFD", class: "etf", sector: "Forex" },
  { symbol: "GBPCAD", name: "GBP/CAD CFD", class: "etf", sector: "Forex" },
  { symbol: "GBPNZD", name: "GBP/NZD CFD", class: "etf", sector: "Forex" },
  { symbol: "EURNZD", name: "EUR/NZD CFD", class: "etf", sector: "Forex" },
  { symbol: "AUDCAD", name: "AUD/CAD CFD", class: "etf", sector: "Forex" },
  { symbol: "AUDNZD", name: "AUD/NZD CFD", class: "etf", sector: "Forex" },
  { symbol: "NZDCAD", name: "NZD/CAD CFD", class: "etf", sector: "Forex" },

  // ETFs
  { symbol: "SPY", name: "SPDR S&P 500 ETF CFD", class: "etf", sector: "ETFs" },
  { symbol: "QQQ", name: "Invesco QQQ Trust CFD", class: "etf", sector: "ETFs" },
  { symbol: "DIA", name: "SPDR Dow Jones Industrial CFD", class: "etf", sector: "ETFs" },
  { symbol: "IWM", name: "iShares Russell 2000 CFD", class: "etf", sector: "ETFs" },
  { symbol: "GLD", name: "SPDR Gold Shares CFD", class: "etf", sector: "ETFs" },
  { symbol: "SLV", name: "iShares Silver Trust CFD", class: "etf", sector: "ETFs" },
  { symbol: "USO", name: "United States Oil Fund CFD", class: "etf", sector: "ETFs" },
  { symbol: "UNG", name: "United States Natural Gas CFD", class: "etf", sector: "ETFs" },
  { symbol: "TLT", name: "iShares 20+ Year Treasury CFD", class: "etf", sector: "ETFs" },
  { symbol: "LQD", name: "iShares iBoxx Investment Grade CFD", class: "etf", sector: "ETFs" },
  { symbol: "HYG", name: "iShares iBoxx High Yield CFD", class: "etf", sector: "ETFs" },
  { symbol: "VWO", name: "Vanguard FTSE Emerging Markets CFD", class: "etf", sector: "ETFs" },
  { symbol: "EEM", name: "iShares MSCI Emerging Markets CFD", class: "etf", sector: "ETFs" },
  { symbol: "EFA", name: "iShares MSCI EAFE ETF CFD", class: "etf", sector: "ETFs" },
  { symbol: "VEA", name: "Vanguard FTSE Developed Markets CFD", class: "etf", sector: "ETFs" },
  { symbol: "VNQ", name: "Vanguard Real Estate ETF CFD", class: "etf", sector: "ETFs" },
  { symbol: "XLF", name: "Financial Select Sector SPDR CFD", class: "etf", sector: "ETFs" },
  { symbol: "XLK", name: "Technology Select Sector SPDR CFD", class: "etf", sector: "ETFs" },
  { symbol: "XLV", name: "Health Care Select Sector SPDR CFD", class: "etf", sector: "ETFs" },
  { symbol: "XLE", name: "Energy Select Sector SPDR CFD", class: "etf", sector: "ETFs" },
  { symbol: "XLI", name: "Industrial Select Sector SPDR CFD", class: "etf", sector: "ETFs" },
  { symbol: "XLB", name: "Materials Select Sector SPDR CFD", class: "etf", sector: "ETFs" },
  { symbol: "XLP", name: "Consumer Staples Select Sector SPDR CFD", class: "etf", sector: "ETFs" },
  { symbol: "XLU", name: "Utilities Select Sector SPDR CFD", class: "etf", sector: "ETFs" },
  { symbol: "XLY", name: "Consumer Discretionary SPDR CFD", class: "etf", sector: "ETFs" },
  { symbol: "ARKK", name: "ARK Innovation ETF CFD", class: "etf", sector: "ETFs" },
  { symbol: "SMH", name: "VanEck Semiconductor ETF CFD", class: "etf", sector: "ETFs" },
  { symbol: "KWEB", name: "KraneShares CSI China Internet CFD", class: "etf", sector: "ETFs" }
];

export function getCapitalAssetCatalog(): AssetRow[] {
  const assets: AssetRow[] = [];

  // 1. Process Cryptos (max leverage 20x for demo CFDs)
  for (const raw of CRYPTO_RAW) {
    const id = stableStaticAssetId(raw.symbol, "crypto");
    const coin = raw.symbol.replace("USD", "").toLowerCase();
    assets.push({
      id,
      symbol: raw.symbol,
      display_name: raw.name,
      asset_class: "crypto",
      provider: "capital",
      provider_ref: raw.symbol,
      logo_url: `https://assets.coincap.io/assets/icons/${coin}@2x.png`,
      sector: "Crypto",
      country: "Global",
      is_tradable: true,
      is_scalpable: true,
      max_leverage_x: 20,
      min_notional_usd: 10,
      status: "active"
    });
  }

  // 2. Process Stocks (max leverage 20x)
  for (const raw of STOCKS_RAW) {
    const id = stableStaticAssetId(raw.symbol, "stock");
    assets.push({
      id,
      symbol: raw.symbol,
      display_name: raw.name,
      asset_class: "stock",
      provider: "capital",
      provider_ref: raw.symbol,
      logo_url: null,
      sector: "Technology",
      country: "US",
      is_tradable: true,
      is_scalpable: true,
      max_leverage_x: 20,
      min_notional_usd: 10,
      status: "active"
    });
  }

  // 3. Process Indices, Commodities, Forex, ETFs (leverage up to 20x)
  for (const raw of INDICES_COMM_FOREX_RAW) {
    const id = stableStaticAssetId(raw.symbol, "etf");
    assets.push({
      id,
      symbol: raw.symbol,
      display_name: raw.name,
      asset_class: "etf",
      provider: "capital",
      provider_ref: raw.symbol,
      logo_url: null,
      sector: raw.sector,
      country: "US",
      is_tradable: true,
      is_scalpable: true,
      max_leverage_x: 20,
      min_notional_usd: 10,
      status: "active"
    });
  }

  return assets;
}
