/**
 * Additional US equities for Markets terminal coverage (S&P 500-style universe).
 * Merged into getCapitalAssetCatalog — deduped by symbol.
 */

export const EXPANDED_STOCKS_RAW: Array<{ symbol: string; name: string; sector?: string }> = [
  { symbol: "BRK.B", name: "Berkshire Hathaway B CFD", sector: "Financials" },
  { symbol: "BRK.A", name: "Berkshire Hathaway A CFD", sector: "Financials" },
  { symbol: "V", name: "Visa Inc. CFD", sector: "Financials" },
  { symbol: "MA", name: "Mastercard Inc. CFD", sector: "Financials" },
  { symbol: "WFC", name: "Wells Fargo CFD", sector: "Financials" },
  { symbol: "C", name: "Citigroup CFD", sector: "Financials" },
  { symbol: "GS", name: "Goldman Sachs CFD", sector: "Financials" },
  { symbol: "MS", name: "Morgan Stanley CFD", sector: "Financials" },
  { symbol: "AXP", name: "American Express CFD", sector: "Financials" },
  { symbol: "BLK", name: "BlackRock CFD", sector: "Financials" },
  { symbol: "SCHW", name: "Charles Schwab CFD", sector: "Financials" },
  { symbol: "CME", name: "CME Group CFD", sector: "Financials" },
  { symbol: "ICE", name: "Intercontinental Exchange CFD", sector: "Financials" },
  { symbol: "MMC", name: "Marsh & McLennan CFD", sector: "Financials" },
  { symbol: "AON", name: "Aon PLC CFD", sector: "Financials" },
  { symbol: "CB", name: "Chubb Ltd CFD", sector: "Financials" },
  { symbol: "PGR", name: "Progressive Corp CFD", sector: "Financials" },
  { symbol: "MET", name: "MetLife CFD", sector: "Financials" },
  { symbol: "AIG", name: "American International Group CFD", sector: "Financials" },
  { symbol: "TRV", name: "Travelers Companies CFD", sector: "Financials" },
  { symbol: "ALL", name: "Allstate Corp CFD", sector: "Financials" },
  { symbol: "PRU", name: "Prudential Financial CFD", sector: "Financials" },
  { symbol: "AFL", name: "Aflac Inc. CFD", sector: "Financials" },
  { symbol: "BK", name: "Bank of New York Mellon CFD", sector: "Financials" },
  { symbol: "STT", name: "State Street Corp CFD", sector: "Financials" },
  { symbol: "USB", name: "U.S. Bancorp CFD", sector: "Financials" },
  { symbol: "PNC", name: "PNC Financial Services CFD", sector: "Financials" },
  { symbol: "TFC", name: "Truist Financial CFD", sector: "Financials" },
  { symbol: "COF", name: "Capital One Financial CFD", sector: "Financials" },
  { symbol: "DFS", name: "Discover Financial CFD", sector: "Financials" },
  { symbol: "SYF", name: "Synchrony Financial CFD", sector: "Financials" },
  { symbol: "RF", name: "Regions Financial CFD", sector: "Financials" },
  { symbol: "KEY", name: "KeyCorp CFD", sector: "Financials" },
  { symbol: "CFG", name: "Citizens Financial Group CFD", sector: "Financials" },
  { symbol: "FITB", name: "Fifth Third Bancorp CFD", sector: "Financials" },
  { symbol: "HBAN", name: "Huntington Bancshares CFD", sector: "Financials" },
  { symbol: "MTB", name: "M&T Bank Corp CFD", sector: "Financials" },
  { symbol: "CINF", name: "Cincinnati Financial CFD", sector: "Financials" },
  { symbol: "L", name: "Loews Corp CFD", sector: "Financials" },
  { symbol: "WRB", name: "W.R. Berkley Corp CFD", sector: "Financials" },
  { symbol: "RE", name: "Everest Group CFD", sector: "Financials" },
  { symbol: "GL", name: "Globe Life Inc. CFD", sector: "Financials" },
  { symbol: "AIZ", name: "Assurant Inc. CFD", sector: "Financials" },
  { symbol: "JKHY", name: "Jack Henry & Associates CFD", sector: "Financials" },
  { symbol: "FIS", name: "Fidelity National Info CFD", sector: "Financials" },
  { symbol: "FISV", name: "Fiserv Inc. CFD", sector: "Financials" },
  { symbol: "GPN", name: "Global Payments CFD", sector: "Financials" },
  { symbol: "CPAY", name: "Corpay Inc. CFD", sector: "Financials" },
  { symbol: "IVZ", name: "Invesco Ltd CFD", sector: "Financials" },
  { symbol: "NTRS", name: "Northern Trust Corp CFD", sector: "Financials" },
  { symbol: "TROW", name: "T. Rowe Price Group CFD", sector: "Financials" },
  { symbol: "BEN", name: "Franklin Resources CFD", sector: "Financials" },
  { symbol: "AMP", name: "Ameriprise Financial CFD", sector: "Financials" },
  { symbol: "RJF", name: "Raymond James Financial CFD", sector: "Financials" },
  { symbol: "LPLA", name: "LPL Financial Holdings CFD", sector: "Financials" },
  { symbol: "CBOE", name: "Cboe Global Markets CFD", sector: "Financials" },
  { symbol: "NDAQ", name: "Nasdaq Inc. CFD", sector: "Financials" },
  { symbol: "CBOE", name: "Cboe Global Markets CFD", sector: "Financials" },
  { symbol: "MCO", name: "Moody's Corp CFD", sector: "Financials" },
  { symbol: "SPGI", name: "S&P Global Inc. CFD", sector: "Financials" },
  { symbol: "MSCI", name: "MSCI Inc. CFD", sector: "Financials" },
  { symbol: "FDS", name: "FactSet Research Systems CFD", sector: "Financials" },
  { symbol: "WTW", name: "Willis Towers Watson CFD", sector: "Financials" },
  { symbol: "BRO", name: "Brown & Brown Inc. CFD", sector: "Financials" },
  { symbol: "AJG", name: "Arthur J. Gallagher CFD", sector: "Financials" },
  { symbol: "EG", name: "Everest Group Ltd CFD", sector: "Financials" },
  { symbol: "ACGL", name: "Arch Capital Group CFD", sector: "Financials" },
  { symbol: "RGA", name: "Reinsurance Group of America CFD", sector: "Financials" },
  { symbol: "LNC", name: "Lincoln National Corp CFD", sector: "Financials" },
  { symbol: "UNM", name: "Unum Group CFD", sector: "Financials" },
  { symbol: "PRI", name: "Primerica Inc. CFD", sector: "Financials" },
  { symbol: "VOO", name: "Vanguard S&P 500 ETF CFD", sector: "ETFs" },
  { symbol: "VTI", name: "Vanguard Total Stock Market ETF CFD", sector: "ETFs" },
  { symbol: "IVV", name: "iShares Core S&P 500 ETF CFD", sector: "ETFs" },
  { symbol: "VUG", name: "Vanguard Growth ETF CFD", sector: "ETFs" },
  { symbol: "VTV", name: "Vanguard Value ETF CFD", sector: "ETFs" },
  { symbol: "SCHD", name: "Schwab US Dividend Equity ETF CFD", sector: "ETFs" },
  { symbol: "JEPI", name: "JPMorgan Equity Premium Income ETF CFD", sector: "ETFs" },
  { symbol: "JEPQ", name: "JPMorgan Nasdaq Equity Premium Income ETF CFD", sector: "ETFs" },
  { symbol: "BOTZ", name: "Global X Robotics & AI ETF CFD", sector: "ETFs" },
  { symbol: "ROBO", name: "Robo Global Robotics ETF CFD", sector: "ETFs" },
  { symbol: "ITA", name: "iShares US Aerospace & Defense ETF CFD", sector: "ETFs" },
  { symbol: "XBI", name: "SPDR S&P Biotech ETF CFD", sector: "ETFs" },
  { symbol: "IBB", name: "iShares Biotechnology ETF CFD", sector: "ETFs" },
  { symbol: "XRT", name: "SPDR S&P Retail ETF CFD", sector: "ETFs" },
  { symbol: "XHB", name: "SPDR S&P Homebuilders ETF CFD", sector: "ETFs" },
  { symbol: "GDX", name: "VanEck Gold Miners ETF CFD", sector: "ETFs" },
  { symbol: "GDXJ", name: "VanEck Junior Gold Miners ETF CFD", sector: "ETFs" },
  { symbol: "SIL", name: "Global X Silver Miners ETF CFD", sector: "ETFs" },
  { symbol: "XOP", name: "SPDR S&P Oil & Gas Exploration ETF CFD", sector: "ETFs" },
  { symbol: "OIH", name: "VanEck Oil Services ETF CFD", sector: "ETFs" },
  { symbol: "TAN", name: "Invesco Solar ETF CFD", sector: "ETFs" },
  { symbol: "ICLN", name: "iShares Global Clean Energy ETF CFD", sector: "ETFs" },
  { symbol: "LIT", name: "Global X Lithium & Battery Tech ETF CFD", sector: "ETFs" },
  { symbol: "URA", name: "Global X Uranium ETF CFD", sector: "ETFs" },
  { symbol: "COPX", name: "Global X Copper Miners ETF CFD", sector: "ETFs" },
  { symbol: "REMX", name: "VanEck Rare Earth/Strategic Metals ETF CFD", sector: "ETFs" },
  { symbol: "MOAT", name: "VanEck Morningstar Wide Moat ETF CFD", sector: "ETFs" },
  { symbol: "QUAL", name: "iShares MSCI USA Quality Factor ETF CFD", sector: "ETFs" },
  { symbol: "MTUM", name: "iShares MSCI USA Momentum Factor ETF CFD", sector: "ETFs" },
  { symbol: "USMV", name: "iShares MSCI USA Min Vol Factor ETF CFD", sector: "ETFs" },
  { symbol: "IJR", name: "iShares Core S&P Small-Cap ETF CFD", sector: "ETFs" },
  { symbol: "VB", name: "Vanguard Small-Cap ETF CFD", sector: "ETFs" },
  { symbol: "VO", name: "Vanguard Mid-Cap ETF CFD", sector: "ETFs" },
  { symbol: "IJH", name: "iShares Core S&P Mid-Cap ETF CFD", sector: "ETFs" },
  { symbol: "MDY", name: "SPDR S&P MidCap 400 ETF CFD", sector: "ETFs" },
  { symbol: "RSP", name: "Invesco S&P 500 Equal Weight ETF CFD", sector: "ETFs" },
  { symbol: "SPLG", name: "SPDR Portfolio S&P 500 ETF CFD", sector: "ETFs" },
  { symbol: "SCHX", name: "Schwab US Large-Cap ETF CFD", sector: "ETFs" },
  { symbol: "SCHB", name: "Schwab US Broad Market ETF CFD", sector: "ETFs" },
  { symbol: "SCHG", name: "Schwab US Large-Cap Growth ETF CFD", sector: "ETFs" },
  { symbol: "SCHV", name: "Schwab US Large-Cap Value ETF CFD", sector: "ETFs" },
  { symbol: "VIG", name: "Vanguard Dividend Appreciation ETF CFD", sector: "ETFs" },
  { symbol: "VYM", name: "Vanguard High Dividend Yield ETF CFD", sector: "ETFs" },
  { symbol: "DVY", name: "iShares Select Dividend ETF CFD", sector: "ETFs" },
  { symbol: "HDV", name: "iShares Core High Dividend ETF CFD", sector: "ETFs" },
  { symbol: "NOBL", name: "ProShares S&P 500 Dividend Aristocrats ETF CFD", sector: "ETFs" },
  { symbol: "DGRO", name: "iShares Core Dividend Growth ETF CFD", sector: "ETFs" },
  { symbol: "SDY", name: "SPDR S&P Dividend ETF CFD", sector: "ETFs" },
  { symbol: "VGT", name: "Vanguard Information Technology ETF CFD", sector: "ETFs" },
  { symbol: "XLRE", name: "Real Estate Select Sector SPDR ETF CFD", sector: "ETFs" },
  { symbol: "XLC", name: "Communication Services Select Sector SPDR ETF CFD", sector: "ETFs" },
  { symbol: "XME", name: "SPDR S&P Metals & Mining ETF CFD", sector: "ETFs" },
  { symbol: "KRE", name: "SPDR S&P Regional Banking ETF CFD", sector: "ETFs" },
  { symbol: "KBE", name: "SPDR S&P Bank ETF CFD", sector: "ETFs" },
  { symbol: "XAR", name: "SPDR S&P Aerospace & Defense ETF CFD", sector: "ETFs" },
  { symbol: "XPH", name: "SPDR S&P Pharmaceuticals ETF CFD", sector: "ETFs" },
  { symbol: "XHS", name: "SPDR S&P Health Care Services ETF CFD", sector: "ETFs" },
  { symbol: "XHE", name: "SPDR S&P Health Care Equipment ETF CFD", sector: "ETFs" },
  { symbol: "XES", name: "SPDR S&P Oil & Gas Equipment ETF CFD", sector: "ETFs" },
  { symbol: "XTL", name: "SPDR S&P Telecom ETF CFD", sector: "ETFs" },
  { symbol: "XSW", name: "SPDR S&P Software & Services ETF CFD", sector: "ETFs" },
  { symbol: "XWEB", name: "SPDR S&P Internet ETF CFD", sector: "ETFs" },
  { symbol: "SOXX", name: "iShares Semiconductor ETF CFD", sector: "ETFs" },
  { symbol: "SOXL", name: "Direxion Daily Semiconductor Bull 3X ETF CFD", sector: "ETFs" },
  { symbol: "SOXS", name: "Direxion Daily Semiconductor Bear 3X ETF CFD", sector: "ETFs" },
  { symbol: "TQQQ", name: "ProShares UltraPro QQQ ETF CFD", sector: "ETFs" },
  { symbol: "SQQQ", name: "ProShares UltraPro Short QQQ ETF CFD", sector: "ETFs" },
  { symbol: "UPRO", name: "ProShares UltraPro S&P500 ETF CFD", sector: "ETFs" },
  { symbol: "SPXU", name: "ProShares UltraPro Short S&P500 ETF CFD", sector: "ETFs" },
  { symbol: "LABU", name: "Direxion Daily S&P Biotech Bull 3X ETF CFD", sector: "ETFs" },
  { symbol: "LABD", name: "Direxion Daily S&P Biotech Bear 3X ETF CFD", sector: "ETFs" },
  { symbol: "FAS", name: "Direxion Daily Financial Bull 3X ETF CFD", sector: "ETFs" },
  { symbol: "FAZ", name: "Direxion Daily Financial Bear 3X ETF CFD", sector: "ETFs" },
  { symbol: "TECL", name: "Direxion Daily Technology Bull 3X ETF CFD", sector: "ETFs" },
  { symbol: "TECS", name: "Direxion Daily Technology Bear 3X ETF CFD", sector: "ETFs" },
  { symbol: "NUGT", name: "Direxion Daily Gold Miners Bull 2X ETF CFD", sector: "ETFs" },
  { symbol: "DUST", name: "Direxion Daily Gold Miners Bear 2X ETF CFD", sector: "ETFs" },
  { symbol: "JNUG", name: "Direxion Daily Jr Gold Miners Bull 2X ETF CFD", sector: "ETFs" },
  { symbol: "JDST", name: "Direxion Daily Jr Gold Miners Bear 2X ETF CFD", sector: "ETFs" },
  { symbol: "UVXY", name: "ProShares Ultra VIX Short-Term Futures ETF CFD", sector: "ETFs" },
  { symbol: "SVXY", name: "ProShares Short VIX Short-Term Futures ETF CFD", sector: "ETFs" },
  { symbol: "VXX", name: "iPath Series B S&P 500 VIX Short-Term Futures ETN CFD", sector: "ETFs" },
  { symbol: "SH", name: "ProShares Short S&P500 ETF CFD", sector: "ETFs" },
  { symbol: "PSQ", name: "ProShares Short QQQ ETF CFD", sector: "ETFs" },
  { symbol: "DOG", name: "ProShares Short Dow30 ETF CFD", sector: "ETFs" },
  { symbol: "RWM", name: "ProShares Short Russell2000 ETF CFD", sector: "ETFs" },
  { symbol: "MUB", name: "iShares National Muni Bond ETF CFD", sector: "ETFs" },
  { symbol: "AGG", name: "iShares Core US Aggregate Bond ETF CFD", sector: "ETFs" },
  { symbol: "BND", name: "Vanguard Total Bond Market ETF CFD", sector: "ETFs" },
  { symbol: "IEF", name: "iShares 7-10 Year Treasury Bond ETF CFD", sector: "ETFs" },
  { symbol: "SHY", name: "iShares 1-3 Year Treasury Bond ETF CFD", sector: "ETFs" },
  { symbol: "TIP", name: "iShares TIPS Bond ETF CFD", sector: "ETFs" },
  { symbol: "LQD", name: "iShares iBoxx Investment Grade Corporate Bond ETF CFD", sector: "ETFs" },
  { symbol: "HYG", name: "iShares iBoxx High Yield Corporate Bond ETF CFD", sector: "ETFs" },
  { symbol: "JNK", name: "SPDR Bloomberg High Yield Bond ETF CFD", sector: "ETFs" },
  { symbol: "EMB", name: "iShares J.P. Morgan USD Emerging Markets Bond ETF CFD", sector: "ETFs" },
  { symbol: "EWJ", name: "iShares MSCI Japan ETF CFD", sector: "ETFs" },
  { symbol: "EWZ", name: "iShares MSCI Brazil ETF CFD", sector: "ETFs" },
  { symbol: "EWY", name: "iShares MSCI South Korea ETF CFD", sector: "ETFs" },
  { symbol: "EWT", name: "iShares MSCI Taiwan ETF CFD", sector: "ETFs" },
  { symbol: "EWH", name: "iShares MSCI Hong Kong ETF CFD", sector: "ETFs" },
  { symbol: "EWG", name: "iShares MSCI Germany ETF CFD", sector: "ETFs" },
  { symbol: "EWU", name: "iShares MSCI United Kingdom ETF CFD", sector: "ETFs" },
  { symbol: "EWC", name: "iShares MSCI Canada ETF CFD", sector: "ETFs" },
  { symbol: "EWA", name: "iShares MSCI Australia ETF CFD", sector: "ETFs" },
  { symbol: "EWS", name: "iShares MSCI Singapore ETF CFD", sector: "ETFs" },
  { symbol: "INDA", name: "iShares MSCI India ETF CFD", sector: "ETFs" },
  { symbol: "MCHI", name: "iShares MSCI China ETF CFD", sector: "ETFs" },
  { symbol: "FXI", name: "iShares China Large-Cap ETF CFD", sector: "ETFs" },
  { symbol: "ASHR", name: "Xtrackers Harvest CSI 300 China A-Shares ETF CFD", sector: "ETFs" },
  { symbol: "RSX", name: "VanEck Russia ETF CFD", sector: "ETFs" },
  { symbol: "EZU", name: "iShares MSCI Eurozone ETF CFD", sector: "ETFs" },
  { symbol: "IEV", name: "iShares Europe ETF CFD", sector: "ETFs" },
  { symbol: "VGK", name: "Vanguard FTSE Europe ETF CFD", sector: "ETFs" },
  { symbol: "VPL", name: "Vanguard FTSE Pacific ETF CFD", sector: "ETFs" },
  { symbol: "VXUS", name: "Vanguard Total International Stock ETF CFD", sector: "ETFs" },
  { symbol: "IXUS", name: "iShares Core MSCI Total International Stock ETF CFD", sector: "ETFs" },
  { symbol: "IEMG", name: "iShares Core MSCI Emerging Markets ETF CFD", sector: "ETFs" },
  { symbol: "VWO", name: "Vanguard FTSE Emerging Markets ETF CFD", sector: "ETFs" },
  { symbol: "SCHE", name: "Schwab Emerging Markets Equity ETF CFD", sector: "ETFs" },
  { symbol: "SCHF", name: "Schwab International Equity ETF CFD", sector: "ETFs" },
  { symbol: "SCHY", name: "Schwab International Dividend Equity ETF CFD", sector: "ETFs" },
  { symbol: "SCHH", name: "Schwab US REIT ETF CFD", sector: "ETFs" },
  { symbol: "VNQI", name: "Vanguard Global ex-US Real Estate ETF CFD", sector: "ETFs" },
  { symbol: "REM", name: "iShares Mortgage Real Estate ETF CFD", sector: "ETFs" },
  { symbol: "MORT", name: "VanEck Mortgage REIT Income ETF CFD", sector: "ETFs" },
  { symbol: "BITO", name: "ProShares Bitcoin Strategy ETF CFD", sector: "ETFs" },
  { symbol: "BITI", name: "ProShares Short Bitcoin Strategy ETF CFD", sector: "ETFs" },
  { symbol: "GBTC", name: "Grayscale Bitcoin Trust ETF CFD", sector: "ETFs" },
  { symbol: "ETHE", name: "Grayscale Ethereum Trust ETF CFD", sector: "ETFs" },
  { symbol: "IBIT", name: "iShares Bitcoin Trust ETF CFD", sector: "ETFs" },
  { symbol: "FBTC", name: "Fidelity Wise Origin Bitcoin Fund ETF CFD", sector: "ETFs" },
  { symbol: "ARKB", name: "ARK 21Shares Bitcoin ETF CFD", sector: "ETFs" },
  { symbol: "ETHA", name: "iShares Ethereum Trust ETF CFD", sector: "ETFs" },
  { symbol: "SHIBUSD", name: "Shiba Inu / USD CFD", sector: "Crypto" },
  { symbol: "TRXUSD", name: "TRON / USD CFD", sector: "Crypto" },
  { symbol: "TONUSD", name: "Toncoin / USD CFD", sector: "Crypto" },
  { symbol: "POLUSD", name: "Polygon / USD CFD", sector: "Crypto" },
  { symbol: "MATICUSD", name: "Polygon / USD CFD", sector: "Crypto" },
  { symbol: "BNBUSD", name: "BNB / USD CFD", sector: "Crypto" },
  { symbol: "XMRUSD", name: "Monero / USD CFD", sector: "Crypto" },
  { symbol: "BCHUSD", name: "Bitcoin Cash / USD CFD", sector: "Crypto" },
  { symbol: "LEOUSD", name: "UNUS SED LEO / USD CFD", sector: "Crypto" },
  { symbol: "OKBUSD", name: "OKB / USD CFD", sector: "Crypto" },
  { symbol: "CROUSD", name: "Cronos / USD CFD", sector: "Crypto" },
  { symbol: "EGLDUSD", name: "MultiversX / USD CFD", sector: "Crypto" },
  { symbol: "FLOWUSD", name: "Flow / USD CFD", sector: "Crypto" },
  { symbol: "XTZUSD", name: "Tezos / USD CFD", sector: "Crypto" },
  { symbol: "KASUSD", name: "Kaspa / USD CFD", sector: "Crypto" },
  { symbol: "RUNEUSD", name: "THORChain / USD CFD", sector: "Crypto" },
  { symbol: "SNXUSD", name: "Synthetix / USD CFD", sector: "Crypto" },
  { symbol: "COMPUSD", name: "Compound / USD CFD", sector: "Crypto" },
  { symbol: "CRVUSD", name: "Curve DAO / USD CFD", sector: "Crypto" },
  { symbol: "SUSHIUSD", name: "SushiSwap / USD CFD", sector: "Crypto" },
  { symbol: "1INCHUSD", name: "1inch / USD CFD", sector: "Crypto" },
  { symbol: "ENSUSD", name: "Ethereum Name Service / USD CFD", sector: "Crypto" },
  { symbol: "BLURUSD", name: "Blur / USD CFD", sector: "Crypto" },
  { symbol: "WLDUSD", name: "Worldcoin / USD CFD", sector: "Crypto" },
  { symbol: "STRKUSD", name: "Starknet / USD CFD", sector: "Crypto" },
  { symbol: "ZECUSD", name: "Zcash / USD CFD", sector: "Crypto" },
  { symbol: "DASHUSD", name: "Dash / USD CFD", sector: "Crypto" },
  { symbol: "NEOUSD", name: "Neo / USD CFD", sector: "Crypto" },
  { symbol: "IOTAUSD", name: "IOTA / USD CFD", sector: "Crypto" },
  { symbol: "ZILUSD", name: "Zilliqa / USD CFD", sector: "Crypto" },
  { symbol: "ENJUSD", name: "Enjin Coin / USD CFD", sector: "Crypto" },
  { symbol: "CHZUSD", name: "Chiliz / USD CFD", sector: "Crypto" },
  { symbol: "BATUSD", name: "Basic Attention Token / USD CFD", sector: "Crypto" },
  { symbol: "ZRXUSD", name: "0x / USD CFD", sector: "Crypto" },
  { symbol: "ANKRUSD", name: "Ankr / USD CFD", sector: "Crypto" },
  { symbol: "SKLUSD", name: "SKALE / USD CFD", sector: "Crypto" },
  { symbol: "OCEANUSD", name: "Ocean Protocol / USD CFD", sector: "Crypto" },
  { symbol: "ROSEUSD", name: "Oasis Network / USD CFD", sector: "Crypto" },
  { symbol: "CELOUSD", name: "Celo / USD CFD", sector: "Crypto" },
  { symbol: "KAVAUSD", name: "Kava / USD CFD", sector: "Crypto" },
  { symbol: "ONEUSD", name: "Harmony / USD CFD", sector: "Crypto" },
  { symbol: "ICXUSD", name: "ICON / USD CFD", sector: "Crypto" },
  { symbol: "QTUMUSD", name: "Qtum / USD CFD", sector: "Crypto" },
  { symbol: "WAVESUSD", name: "Waves / USD CFD", sector: "Crypto" },
  { symbol: "KSMUSD", name: "Kusama / USD CFD", sector: "Crypto" },
  { symbol: "YFIUSD", name: "yearn.finance / USD CFD", sector: "Crypto" },
  { symbol: "UMAUSD", name: "UMA / USD CFD", sector: "Crypto" },
  { symbol: "BALUSD", name: "Balancer / USD CFD", sector: "Crypto" },
  { symbol: "RENUSD", name: "Ren / USD CFD", sector: "Crypto" },
  { symbol: "LRCUSD", name: "Loopring / USD CFD", sector: "Crypto" },
  { symbol: "STORJUSD", name: "Storj / USD CFD", sector: "Crypto" },
  { symbol: "OXTUSD", name: "Orchid / USD CFD", sector: "Crypto" },
  { symbol: "NKNUSD", name: "NKN / USD CFD", sector: "Crypto" },
  { symbol: "BANDUSD", name: "Band Protocol / USD CFD", sector: "Crypto" },
  { symbol: "NMRUSD", name: "Numeraire / USD CFD", sector: "Crypto" },
  { symbol: "CVCUSD", name: "Civic / USD CFD", sector: "Crypto" },
  { symbol: "DNTUSD", name: "district0x / USD CFD", sector: "Crypto" },
  { symbol: "LOOMUSD", name: "Loom Network / USD CFD", sector: "Crypto" },
  { symbol: "POWRUSD", name: "Power Ledger / USD CFD", sector: "Crypto" },
  { symbol: "REQUSD", name: "Request / USD CFD", sector: "Crypto" },
  { symbol: "DATAUSD", name: "Streamr / USD CFD", sector: "Crypto" },
  { symbol: "AMPLUSD", name: "Ampleforth / USD CFD", sector: "Crypto" },
  { symbol: "USDTUSD", name: "Tether / USD CFD", sector: "Crypto" },
  { symbol: "USDCUSD", name: "USD Coin / USD CFD", sector: "Crypto" },
  { symbol: "DAIUSD", name: "Dai / USD CFD", sector: "Crypto" },
  { symbol: "USDNZD", name: "USD/NZD CFD", sector: "Forex" },
  { symbol: "USDSEK", name: "USD/SEK CFD", sector: "Forex" },
  { symbol: "USDNOK", name: "USD/NOK CFD", sector: "Forex" },
  { symbol: "USDDKK", name: "USD/DKK CFD", sector: "Forex" },
  { symbol: "USDPLN", name: "USD/PLN CFD", sector: "Forex" },
  { symbol: "USDHUF", name: "USD/HUF CFD", sector: "Forex" },
  { symbol: "USDZAR", name: "USD/ZAR CFD", sector: "Forex" },
  { symbol: "USDMXN", name: "USD/MXN CFD", sector: "Forex" },
  { symbol: "USDBRL", name: "USD/BRL CFD", sector: "Forex" },
  { symbol: "USDTRY", name: "USD/TRY CFD", sector: "Forex" },
  { symbol: "USDSGD", name: "USD/SGD CFD", sector: "Forex" },
  { symbol: "USDHKD", name: "USD/HKD CFD", sector: "Forex" },
  { symbol: "EURGBP", name: "EUR/GBP CFD", sector: "Forex" },
  { symbol: "EURCHF", name: "EUR/CHF CFD", sector: "Forex" },
  { symbol: "EURCAD", name: "EUR/CAD CFD", sector: "Forex" },
  { symbol: "EURSEK", name: "EUR/SEK CFD", sector: "Forex" },
  { symbol: "EURNOK", name: "EUR/NOK CFD", sector: "Forex" },
  { symbol: "EURPLN", name: "EUR/PLN CFD", sector: "Forex" },
  { symbol: "EURHUF", name: "EUR/HUF CFD", sector: "Forex" },
  { symbol: "EURTRY", name: "EUR/TRY CFD", sector: "Forex" },
  { symbol: "GBPJPY", name: "GBP/JPY CFD", sector: "Forex" },
  { symbol: "GBPCHF", name: "GBP/CHF CFD", sector: "Forex" },
  { symbol: "GBPCAD", name: "GBP/CAD CFD", sector: "Forex" },
  { symbol: "GBPNZD", name: "GBP/NZD CFD", sector: "Forex" },
  { symbol: "GBPSEK", name: "GBP/SEK CFD", sector: "Forex" },
  { symbol: "GBPNOK", name: "GBP/NOK CFD", sector: "Forex" },
  { symbol: "AUDJPY", name: "AUD/JPY CFD", sector: "Forex" },
  { symbol: "AUDCHF", name: "AUD/CHF CFD", sector: "Forex" },
  { symbol: "AUDCAD", name: "AUD/CAD CFD", sector: "Forex" },
  { symbol: "AUDNZD", name: "AUD/NZD CFD", sector: "Forex" },
  { symbol: "CADCHF", name: "CAD/CHF CFD", sector: "Forex" },
  { symbol: "CADJPY", name: "CAD/JPY CFD", sector: "Forex" },
  { symbol: "CHFJPY", name: "CHF/JPY CFD", sector: "Forex" },
  { symbol: "NZDJPY", name: "NZD/JPY CFD", sector: "Forex" },
  { symbol: "NZDCHF", name: "NZD/CHF CFD", sector: "Forex" },
  { symbol: "NZDCAD", name: "NZD/CAD CFD", sector: "Forex" },
  { symbol: "XPTUSD", name: "Platinum Spot CFD", sector: "Commodities" },
  { symbol: "XPDUSD", name: "Palladium Spot CFD", sector: "Commodities" },
  { symbol: "XCUUSD", name: "Copper Spot CFD", sector: "Commodities" },
  { symbol: "NGAS", name: "Natural Gas Spot CFD", sector: "Commodities" },
  { symbol: "HEATOIL", name: "Heating Oil CFD", sector: "Commodities" },
  { symbol: "GASOLINE", name: "Gasoline RBOB CFD", sector: "Commodities" },
  { symbol: "COTTON2", name: "Cotton No.2 CFD", sector: "Commodities" },
  { symbol: "LUMBER", name: "Lumber CFD", sector: "Commodities" },
  { symbol: "ORANGE", name: "Orange Juice CFD", sector: "Commodities" },
  { symbol: "LIVECATTLE", name: "Live Cattle CFD", sector: "Commodities" },
  { symbol: "LEANHOGS", name: "Lean Hogs CFD", sector: "Commodities" },
  { symbol: "FEEDERCATTLE", name: "Feeder Cattle CFD", sector: "Commodities" },
  { symbol: "RICE", name: "Rough Rice CFD", sector: "Commodities" },
  { symbol: "OATS", name: "Oats CFD", sector: "Commodities" },
  { symbol: "CANOLA", name: "Canola CFD", sector: "Commodities" },
  { symbol: "LITHIUM", name: "Lithium CFD", sector: "Commodities" },
  { symbol: "ALUMINUM", name: "Aluminum CFD", sector: "Commodities" },
  { symbol: "NICKEL", name: "Nickel CFD", sector: "Commodities" },
  { symbol: "ZINC", name: "Zinc CFD", sector: "Commodities" },
  { symbol: "LEAD", name: "Lead CFD", sector: "Commodities" },
  { symbol: "TIN", name: "Tin CFD", sector: "Commodities" },
  { symbol: "US2000", name: "US Russell 2000 CFD", sector: "Indices" },
  { symbol: "US400", name: "US MidCap 400 CFD", sector: "Indices" },
  { symbol: "US600", name: "US SmallCap 600 CFD", sector: "Indices" },
  { symbol: "EUROSTOXX50", name: "Euro Stoxx 50 CFD", sector: "Indices" },
  { symbol: "STOXX600", name: "Stoxx Europe 600 CFD", sector: "Indices" },
  { symbol: "DAX", name: "Germany DAX CFD", sector: "Indices" },
  { symbol: "CAC40", name: "France CAC 40 CFD", sector: "Indices" },
  { symbol: "FTSE100", name: "UK FTSE 100 CFD", sector: "Indices" },
  { symbol: "FTSE250", name: "UK FTSE 250 CFD", sector: "Indices" },
  { symbol: "IBEX35", name: "Spain IBEX 35 CFD", sector: "Indices" },
  { symbol: "MIB40", name: "Italy FTSE MIB CFD", sector: "Indices" },
  { symbol: "SMI", name: "Switzerland SMI CFD", sector: "Indices" },
  { symbol: "AEX", name: "Netherlands AEX CFD", sector: "Indices" },
  { symbol: "BEL20", name: "Belgium BEL 20 CFD", sector: "Indices" },
  { symbol: "OMX30", name: "Sweden OMX 30 CFD", sector: "Indices" },
  { symbol: "OSEBX", name: "Norway OBX CFD", sector: "Indices" },
  { symbol: "NIKKEI", name: "Japan Nikkei 225 CFD", sector: "Indices" },
  { symbol: "TOPIX", name: "Japan TOPIX CFD", sector: "Indices" },
  { symbol: "KOSPI", name: "South Korea KOSPI CFD", sector: "Indices" },
  { symbol: "TWSE", name: "Taiwan TAIEX CFD", sector: "Indices" },
  { symbol: "SENSEX", name: "India SENSEX CFD", sector: "Indices" },
  { symbol: "NIFTY50", name: "India NIFTY 50 CFD", sector: "Indices" },
  { symbol: "ASX200", name: "Australia ASX 200 CFD", sector: "Indices" },
  { symbol: "NZ50", name: "New Zealand NZX 50 CFD", sector: "Indices" },
  { symbol: "STI", name: "Singapore STI CFD", sector: "Indices" },
  { symbol: "SET", name: "Thailand SET CFD", sector: "Indices" },
  { symbol: "JCI", name: "Indonesia JCI CFD", sector: "Indices" },
  { symbol: "KLCI", name: "Malaysia KLCI CFD", sector: "Indices" },
  { symbol: "PSEI", name: "Philippines PSEi CFD", sector: "Indices" },
  { symbol: "VNINDEX", name: "Vietnam VN-Index CFD", sector: "Indices" },
  { symbol: "BOVESPA", name: "Brazil Bovespa CFD", sector: "Indices" },
  { symbol: "IPC", name: "Mexico IPC CFD", sector: "Indices" },
  { symbol: "MERVAL", name: "Argentina MERVAL CFD", sector: "Indices" },
  { symbol: "IPSA", name: "Chile IPSA CFD", sector: "Indices" },
  { symbol: "COLCAP", name: "Colombia COLCAP CFD", sector: "Indices" },
  { symbol: "RTS", name: "Russia RTS CFD", sector: "Indices" },
  { symbol: "MOEX", name: "Russia MOEX CFD", sector: "Indices" },
  { symbol: "SA40", name: "South Africa Top 40 CFD", sector: "Indices" },
  { symbol: "EGX30", name: "Egypt EGX 30 CFD", sector: "Indices" },
  { symbol: "TADAWUL", name: "Saudi Tadawul All Share CFD", sector: "Indices" },
  { symbol: "DFM", name: "Dubai DFM CFD", sector: "Indices" },
  { symbol: "ADX", name: "Abu Dhabi ADX CFD", sector: "Indices" },
  { symbol: "QATAR", name: "Qatar QE CFD", sector: "Indices" },
  { symbol: "KUWAIT", name: "Kuwait All Share CFD", sector: "Indices" },
  { symbol: "BIST100", name: "Turkey BIST 100 CFD", sector: "Indices" },
  { symbol: "WIG20", name: "Poland WIG20 CFD", sector: "Indices" },
  { symbol: "PX", name: "Czech PX CFD", sector: "Indices" },
  { symbol: "BUX", name: "Hungary BUX CFD", sector: "Indices" },
  { symbol: "ATX", name: "Austria ATX CFD", sector: "Indices" },
  { symbol: "PSI20", name: "Portugal PSI 20 CFD", sector: "Indices" },
  { symbol: "ISEQ", name: "Ireland ISEQ CFD", sector: "Indices" },
  { symbol: "OMXC25", name: "Denmark OMX C25 CFD", sector: "Indices" },
  { symbol: "OMXS30", name: "Sweden OMXS30 CFD", sector: "Indices" },
  { symbol: "OMXN40", name: "Norway OBX CFD", sector: "Indices" },
  { symbol: "OMXV20", name: "Finland OMXH25 CFD", sector: "Indices" },
  { symbol: "OMXT", name: "Baltic OMX Tallinn CFD", sector: "Indices" },
  { symbol: "OMXR", name: "Baltic OMX Riga CFD", sector: "Indices" },
  { symbol: "OMXV", name: "Baltic OMX Vilnius CFD", sector: "Indices" },
];
