import { companies } from "@/lib/companies";

// Comprehensive catalog-wide stock & ETF ticker-to-domain mapping
const CUSTOM_DOMAINS: Record<string, string> = {
  // Individual Stocks
  AAPL: "apple.com",
  MSFT: "microsoft.com",
  TSLA: "tesla.com",
  NVDA: "nvidia.com",
  NVIDIA: "nvidia.com",
  AMZN: "amazon.com",
  GOOGL: "abc.xyz",
  GOOG: "abc.xyz",
  META: "meta.com",
  NFLX: "netflix.com",
  AMD: "amd.com",
  INTC: "intel.com",
  PYPL: "paypal.com",
  DIS: "disney.com",
  SBUX: "starbucks.com",
  NKE: "nike.com",
  KO: "coca-colacompany.com",
  PEP: "pepsico.com",
  WMT: "walmart.com",
  TSM: "tsmc.com",
  BABA: "alibaba.com",
  ASML: "asml.com",
  JPM: "jpmorganchase.com",
  BAC: "bankofamerica.com",
  V: "visa.com",
  MA: "mastercard.com",
  LLY: "lilly.com",
  UNH: "uhc.com",
  HD: "homedepot.com",
  COST: "costco.com",
  CVX: "chevron.com",
  XOM: "exxonmobil.com",
  JNJ: "jnj.com",
  PG: "pg.com",
  MRK: "merck.com",
  PFE: "pfizer.com",
  ABBV: "abbvie.com",
  AVGO: "broadcom.com",
  ADBE: "adobe.com",
  CRM: "salesforce.com",
  ORCL: "oracle.com",
  CSCO: "cisco.com",
  QCOM: "qualcomm.com",
  TXN: "ti.com",
  AMAT: "appliedmaterials.com",
  MU: "micron.com",
  LRCX: "lamresearch.com",
  NOW: "servicenow.com",
  PANW: "paloaltonetworks.com",
  FTNT: "fortinet.com",
  CRWD: "crowdstrike.com",
  DDOG: "datadoghq.com",
  NET: "cloudflare.com",
  OKTA: "okta.com",
  SNOW: "snowflake.com",
  ABNB: "airbnb.com",
  UBER: "uber.com",
  LYFT: "lyft.com",
  DASH: "doordash.com",
  CART: "instacart.com",
  COIN: "coinbase.com",
  HOOD: "robinhood.com",
  SQ: "block.xyz",
  SOFI: "sofi.com",
  PLTR: "palantir.com",
  RIVN: "rivian.com",
  LCID: "lucidmotors.com",
  NIO: "nio.com",
  XPEV: "xpeng.com",
  LI: "liauto.com",
  JD: "jd.com",
  PDD: "pddholdings.com",
  BIDU: "baidu.com",
  SE: "seagroup.com",
  MELI: "mercadolibre.com",
  SHOP: "shopify.com",
  SPOT: "spotify.com",
  ROKU: "roku.com",
  ZM: "zoom.us",
  DOCU: "docusign.com",
  DKNG: "draftkings.com",
  GME: "gamestop.com",
  AMC: "amctheatres.com",
  MARA: "mara.com",
  RIOT: "riotplatforms.com",
  MSTR: "microstrategy.com",
  GE: "ge.com",
  F: "ford.com",
  GM: "gm.com",
  CAT: "caterpillar.com",
  DE: "deere.com",
  MMM: "3m.com",
  HON: "honeywell.com",
  BA: "boeing.com",
  LMT: "lockheedmartin.com",
  RTX: "rtx.com",
  NOC: "northropgrumman.com",
  GD: "gd.com",
  BP: "bp.com",
  SHEL: "shell.com",
  COP: "conocophillips.com",
  SLB: "slb.com",
  HAL: "halliburton.com",
  UNP: "up.com",
  UPS: "ups.com",
  FDX: "fedex.com",
  T: "att.com",
  VZ: "verizon.com",
  TMUS: "t-mobile.com",
  CMG: "chipotle.com",
  MCD: "mcdonalds.com",
  NPSNY: "naspers.com",
  TENCENT: "tencent.com",
  SONY: "sony.com",
  HMC: "honda.com",
  TOYOF: "toyota.com",
  AIRFP: "airbus.com",
  BMW: "bmw.com",
  DAI: "mercedes-benz.com",
  VOW: "volkswagen.com",

  // ETFs
  SPY: "ssga.com",
  QQQ: "invesco.com",
  DIA: "ssga.com",
  IWM: "ishares.com",
  GLD: "ssga.com",
  SLV: "ishares.com",
  USO: "uscafunds.com",
  UNG: "uscafunds.com",
  TLT: "ishares.com",
  LQD: "ishares.com",
  HYG: "ishares.com",
  VWO: "vanguard.com",
  EEM: "ishares.com",
  EFA: "ishares.com",
  VEA: "vanguard.com",
  VNQ: "vanguard.com",
  XLF: "ssga.com",
  XLK: "ssga.com",
  XLV: "ssga.com",
  XLE: "ssga.com",
  XLI: "ssga.com",
  XLB: "ssga.com",
  XLP: "ssga.com",
  XLU: "ssga.com",
  XLY: "ssga.com",
  ARKK: "ark-invest.com",
  SMH: "vaneck.com",
  KWEB: "kraneshares.com"
};

const domainByTicker = new Map(
  companies.map((c) => [c.ticker.toUpperCase(), c.domain] as const)
);

export function getCompanyDomain(ticker: string): string | null {
  const sym = ticker.toUpperCase();
  return CUSTOM_DOMAINS[sym] ?? domainByTicker.get(sym) ?? null;
}
