export interface Company {
  ticker: string;
  name: string;
  domain: string;
  sector: string;
}

export const sectors = [
  "All",
  "ETF",
  "Technology",
  "Finance",
  "Healthcare",
  "Consumer",
  "Energy",
  "Industrial",
  "Telecom",
  "Media",
  "Crypto"
] as const;
export type Sector = (typeof sectors)[number];

export const companies: Company[] = [
  // ETFs - Priority for AI portfolios (diversified, lower risk)
  { ticker: "VOO", name: "Vanguard S&P 500 ETF", domain: "vanguard.com", sector: "ETF" },
  { ticker: "VTI", name: "Vanguard Total Stock Market ETF", domain: "vanguard.com", sector: "ETF" },
  { ticker: "QQQ", name: "Invesco QQQ Trust (Nasdaq-100)", domain: "invesco.com", sector: "ETF" },
  { ticker: "SPY", name: "SPDR S&P 500 ETF Trust", domain: "ssga.com", sector: "ETF" },
  { ticker: "IVV", name: "iShares Core S&P 500 ETF", domain: "ishares.com", sector: "ETF" },
  { ticker: "VGT", name: "Vanguard Information Technology ETF", domain: "vanguard.com", sector: "ETF" },
  { ticker: "SCHD", name: "Schwab U.S. Dividend Equity ETF", domain: "schwab.com", sector: "ETF" },
  { ticker: "VYM", name: "Vanguard High Dividend Yield ETF", domain: "vanguard.com", sector: "ETF" },
  { ticker: "ARKK", name: "ARK Innovation ETF", domain: "ark-invest.com", sector: "ETF" },
  { ticker: "VUG", name: "Vanguard Growth ETF", domain: "vanguard.com", sector: "ETF" },
  { ticker: "VTV", name: "Vanguard Value ETF", domain: "vanguard.com", sector: "ETF" },
  { ticker: "VXUS", name: "Vanguard Total International Stock ETF", domain: "vanguard.com", sector: "ETF" },
  { ticker: "BND", name: "Vanguard Total Bond Market ETF", domain: "vanguard.com", sector: "ETF" },
  { ticker: "AGG", name: "iShares Core U.S. Aggregate Bond ETF", domain: "ishares.com", sector: "ETF" },
  { ticker: "VNQ", name: "Vanguard Real Estate ETF", domain: "vanguard.com", sector: "ETF" },
  { ticker: "XLK", name: "Technology Select Sector SPDR Fund", domain: "ssga.com", sector: "ETF" },
  { ticker: "XLF", name: "Financial Select Sector SPDR Fund", domain: "ssga.com", sector: "ETF" },
  { ticker: "XLV", name: "Health Care Select Sector SPDR Fund", domain: "ssga.com", sector: "ETF" },
  { ticker: "XLE", name: "Energy Select Sector SPDR Fund", domain: "ssga.com", sector: "ETF" },
  { ticker: "XLY", name: "Consumer Discretionary Select SPDR", domain: "ssga.com", sector: "ETF" },
  { ticker: "XLP", name: "Consumer Staples Select Sector SPDR", domain: "ssga.com", sector: "ETF" },
  { ticker: "IEMG", name: "iShares Core MSCI Emerging Markets ETF", domain: "ishares.com", sector: "ETF" },
  { ticker: "EFA", name: "iShares MSCI EAFE ETF", domain: "ishares.com", sector: "ETF" },
  { ticker: "GLD", name: "SPDR Gold Shares", domain: "ssga.com", sector: "ETF" },
  { ticker: "SLV", name: "iShares Silver Trust", domain: "ishares.com", sector: "ETF" },
  { ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF", domain: "ishares.com", sector: "ETF" },
  { ticker: "JEPI", name: "JPMorgan Equity Premium Income ETF", domain: "jpmorgan.com", sector: "ETF" },
  { ticker: "JEPQ", name: "JPMorgan Nasdaq Equity Premium Income ETF", domain: "jpmorgan.com", sector: "ETF" },
  { ticker: "SPLG", name: "SPDR Portfolio S&P 500 ETF", domain: "ssga.com", sector: "ETF" },
  { ticker: "SPHD", name: "Invesco S&P 500 High Dividend Low Volatility ETF", domain: "invesco.com", sector: "ETF" },

  // Individual Stocks
  { ticker: "AAPL", name: "Apple", domain: "apple.com", sector: "Technology" },
  { ticker: "MSFT", name: "Microsoft", domain: "microsoft.com", sector: "Technology" },
  { ticker: "GOOGL", name: "Alphabet", domain: "abc.xyz", sector: "Technology" },
  { ticker: "AMZN", name: "Amazon", domain: "amazon.com", sector: "Consumer" },
  { ticker: "META", name: "Meta", domain: "meta.com", sector: "Technology" },
  { ticker: "NVDA", name: "NVIDIA", domain: "nvidia.com", sector: "Technology" },
  { ticker: "TSLA", name: "Tesla", domain: "tesla.com", sector: "Consumer" },
  { ticker: "NFLX", name: "Netflix", domain: "netflix.com", sector: "Media" },
  { ticker: "ORCL", name: "Oracle", domain: "oracle.com", sector: "Technology" },
  { ticker: "ADBE", name: "Adobe", domain: "adobe.com", sector: "Technology" },
  { ticker: "CRM", name: "Salesforce", domain: "salesforce.com", sector: "Technology" },
  { ticker: "INTC", name: "Intel", domain: "intel.com", sector: "Technology" },
  { ticker: "AMD", name: "AMD", domain: "amd.com", sector: "Technology" },
  { ticker: "QCOM", name: "Qualcomm", domain: "qualcomm.com", sector: "Technology" },
  { ticker: "UBER", name: "Uber", domain: "uber.com", sector: "Technology" },
  { ticker: "SHOP", name: "Shopify", domain: "shopify.com", sector: "Technology" },
  { ticker: "JPM", name: "JPMorgan Chase", domain: "jpmorganchase.com", sector: "Finance" },
  { ticker: "BAC", name: "Bank of America", domain: "bankofamerica.com", sector: "Finance" },
  { ticker: "WFC", name: "Wells Fargo", domain: "wellsfargo.com", sector: "Finance" },
  { ticker: "GS", name: "Goldman Sachs", domain: "goldmansachs.com", sector: "Finance" },
  { ticker: "V", name: "Visa", domain: "visa.com", sector: "Finance" },
  { ticker: "MA", name: "Mastercard", domain: "mastercard.com", sector: "Finance" },
  { ticker: "PYPL", name: "PayPal", domain: "paypal.com", sector: "Finance" },
  { ticker: "BRK-B", name: "Berkshire Hathaway", domain: "berkshirehathaway.com", sector: "Finance" },
  { ticker: "JNJ", name: "Johnson & Johnson", domain: "jnj.com", sector: "Healthcare" },
  { ticker: "PFE", name: "Pfizer", domain: "pfizer.com", sector: "Healthcare" },
  { ticker: "MRK", name: "Merck", domain: "merck.com", sector: "Healthcare" },
  { ticker: "ABBV", name: "AbbVie", domain: "abbvie.com", sector: "Healthcare" },
  { ticker: "UNH", name: "UnitedHealth", domain: "uhc.com", sector: "Healthcare" },
  { ticker: "KO", name: "Coca-Cola", domain: "coca-colacompany.com", sector: "Consumer" },
  { ticker: "PEP", name: "PepsiCo", domain: "pepsico.com", sector: "Consumer" },
  { ticker: "MCD", name: "McDonald's", domain: "mcdonalds.com", sector: "Consumer" },
  { ticker: "NKE", name: "Nike", domain: "nike.com", sector: "Consumer" },
  { ticker: "SBUX", name: "Starbucks", domain: "starbucks.com", sector: "Consumer" },
  { ticker: "WMT", name: "Walmart", domain: "walmart.com", sector: "Consumer" },
  { ticker: "XOM", name: "Exxon Mobil", domain: "exxonmobil.com", sector: "Energy" },
  { ticker: "CVX", name: "Chevron", domain: "chevron.com", sector: "Energy" },
  { ticker: "COP", name: "ConocoPhillips", domain: "conocophillips.com", sector: "Energy" },
  { ticker: "BA", name: "Boeing", domain: "boeing.com", sector: "Industrial" },
  { ticker: "CAT", name: "Caterpillar", domain: "caterpillar.com", sector: "Industrial" },
  { ticker: "GE", name: "GE Aerospace", domain: "geaerospace.com", sector: "Industrial" },
  { ticker: "HON", name: "Honeywell", domain: "honeywell.com", sector: "Industrial" },
  { ticker: "T", name: "AT&T", domain: "att.com", sector: "Telecom" },
  { ticker: "VZ", name: "Verizon", domain: "verizon.com", sector: "Telecom" },
  { ticker: "DIS", name: "Disney", domain: "disney.com", sector: "Media" },
  { ticker: "SONY", name: "Sony Group", domain: "sony.com", sector: "Media" },

  // Crypto (kept alongside companies as requested)
  { ticker: "BTC-USD", name: "Bitcoin", domain: "bitcoin.org", sector: "Crypto" },
  { ticker: "ETH-USD", name: "Ethereum", domain: "ethereum.org", sector: "Crypto" },
  { ticker: "BNB-USD", name: "BNB", domain: "bnbchain.org", sector: "Crypto" },
  { ticker: "SOL-USD", name: "Solana", domain: "solana.com", sector: "Crypto" },
  { ticker: "XRP-USD", name: "XRP", domain: "ripple.com", sector: "Crypto" },
  { ticker: "ADA-USD", name: "Cardano", domain: "cardano.org", sector: "Crypto" },
  { ticker: "DOGE-USD", name: "Dogecoin", domain: "dogecoin.com", sector: "Crypto" },
  { ticker: "AVAX-USD", name: "Avalanche", domain: "avax.network", sector: "Crypto" },
  { ticker: "DOT-USD", name: "Polkadot", domain: "polkadot.network", sector: "Crypto" },
  { ticker: "LINK-USD", name: "Chainlink", domain: "chain.link", sector: "Crypto" },
  { ticker: "MATIC-USD", name: "Polygon", domain: "polygon.technology", sector: "Crypto" },
  { ticker: "UNI7083-USD", name: "Uniswap", domain: "uniswap.org", sector: "Crypto" },
  { ticker: "SHIB-USD", name: "Shiba Inu", domain: "shibatoken.com", sector: "Crypto" },
  { ticker: "LTC-USD", name: "Litecoin", domain: "litecoin.org", sector: "Crypto" },
  { ticker: "ATOM-USD", name: "Cosmos", domain: "cosmos.network", sector: "Crypto" },
  { ticker: "NEAR-USD", name: "NEAR Protocol", domain: "near.org", sector: "Crypto" },
  { ticker: "FIL-USD", name: "Filecoin", domain: "filecoin.io", sector: "Crypto" },
  { ticker: "AAVE-USD", name: "Aave", domain: "aave.com", sector: "Crypto" },
  { ticker: "ALGO-USD", name: "Algorand", domain: "algorand.com", sector: "Crypto" },
  { ticker: "XLM-USD", name: "Stellar", domain: "stellar.org", sector: "Crypto" }
];
